### ISSUE TITLE
feat(glint): support creating component signature for template only components .gts files.

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#1227]
Current support is for only .gts files with component backing classes. We should support template only components in a .gts files.

This feature should support:
- [X] Adding an argument to an existing signature. Addressed by #1276 
- [X] Adding an `Args` property to an empty signature.  Addressed by #1276 
- [X] Generate a complete signature if none exists. #1278
- [X] Add support for type `TOC` <-- Must Have, Necessary for internal adopters of TemplateOnlyComponents #1278 
- [ ] Add support for renamed type <-- Should Have, This doesn't happen often but could happen.
- [ ] Add support for missing default export <-- Could Have, Need to evaluate this use case.
