### ISSUE TITLE
feat: rehearsal migrate --report

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#438]
This feature is to track the state of where a project is in a migration. There are 3 scenarios we need to solve for:

### Scenario 1: Tightening Over Time

In this scenario a team has ran `rehearsal migrate` across their entire code base and have a SARIF report file in their code base. As teams start to fix issues a couple of things will happen:

1. `@ts-expect-error` comments will be removed as they are fixed
2. Fixing issues and editing the project's file will shift the line and col numbers around causing the report to point to the wrong thing

### Scenario 2: Partial Migration

In this scenario an application team has chosen not to move to TypeScript all in one approach but instead are taking a more piecemeal approach. This is a superset of scenario 1 but with the added edition of needing to know how many more files need to be converted to TS.

## Tasks

Because making progress and tightening types up over time causes issues with the report and people may be taking different approaches to migration we need the ability to re-generate the report so it is accurate. By adding this functionality we also open up the ability for application teams to use cron or pre-commit hooks to ensure the report is fresh.

I believe the tasks are something like the following although this may not be fully exhaustive:

- [ ] Gather up all the TypeScript & JavaScript files if there are any files in the project
- [ ] Make migrate aware of the `--report` flag
- [ ] Use the [ReRehearsePlugin](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/re-rehearse.plugin.ts) to remove all the `@ts-expect-error @rehearsal TODO` comments
- [ ] Run the FormatPlugin on the TS files
- [ ] Update the [diagnostic-check.plugin.ts](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/diagnostic-check.plugin.ts) or create a new plugin that pushes entries into the report  to track any unmigrated JS files. These probably need to be reported or tagged differently.
- [ ] Run the [diagnostic-check.plugin.ts](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/plugins/src/plugins/diagnostic-check.plugin.ts) to collect all the existing errors
- [ ] Write the report back

## Done

To close out this feature we need to be able to regenerate the report to track the progress of a migration by both fixing `@ts-expect-error` comments and files migrated

## Open Questions

1. By adding JS file tracking into the mix we diverging as to what `rehearsal migrate` gives you by the default. We need to think about how to resolve that.

**Comment by brendaHuang** [comment]
@chadhietala @lynchbomb What about a separate command such as `rehearsal report` instead of `rehearsal migrate --report`? People who do incremental upgrade may use this command as well.

**Comment by brendaHuang** [comment]
Or `report scan`?

**Comment by brendaHuang** [comment]
I do see the advantage of `rehearsal migrate --report`. We can also have `rehearsal upgrade --report`, which replicates what the first command does.

**Comment by lynchbomb** [comment]
Likely the implementation with `--report` is run the migration cli with all plugins EXCEPT `DiagnosticFixPlugin`. Additionally we need a new plugin that we would include here to remove all the rehearsal ts-expect-error comments.

**Comment by brendaHuang** [comment]
Per discussion with @lynchbomb:

1. the command option will be renamed `rehearsal migrate --regen`
2. a regen flow that consists of:
   -- rehearsal plugin
   -- diagnostic check plugin
   -- lint check plugin

Since this command options checks migration status, assuming migration has started or done,

1. We won't add ts config or  eslint config
2. We won't handle js files. We will only traverse ts files.

**Comment by lynchbomb** [comment]
Linking duplicate issue #635
